#!/usr/bin/env python3
"""
Generate NixOS configurations dynamically from cluster.json

This script reads cluster.json and generates:
1. Host-specific configuration files
2. Updated flake.nix with all nodes
3. Hardware configuration templates

Usage: python3 scripts/generate-configs.py [--cleanup-k3s]
"""

import json
from pathlib import Path

def load_cluster_config():
    """Load cluster configuration from cluster.json"""
    with open('cluster.json', 'r') as f:
        return json.load(f)

def create_host_config(node_name, node_config, server_config, agent_config):
    """Create host-specific configuration.nix"""
    role = node_config['role']
    template = server_config if role == "server" else agent_config
    
    # Determine k3s configuration based on role
    if role == "server":
        k3s_config = f"""
  # k3s server configuration (control plane)
  services.k3s = {{
    enable = true;
    role = "server";
    clusterInit = {str(template['k3s']['clusterInit']).lower()};
    extraFlags = toString [
{chr(10).join(f'      "{flag}"' for flag in template['k3s']['extraFlags'])}
    ];
  }};

  # Open k3s ports in firewall
  networking.firewall = {{
    allowedTCPPorts = [
      6443 # Kubernetes API server
      10250 # Kubelet metrics
    ];
    allowedUDPPorts = [
      8472 # Flannel VXLAN
    ];
  }};"""
    else:  # agent
        k3s_config = f"""
  # k3s agent configuration (worker node)
  services.k3s = {{
    enable = true;
    role = "agent";
    serverAddr = "https://192.168.1.141:6443"; # Point to nuc1 (server)
    tokenFile = "{template['k3s']['tokenFile']}";
    extraFlags = toString [
{chr(10).join(f'      "{flag}"' for flag in template['k3s']['extraFlags'])}
    ];
  }};

  # Open k3s ports in firewall
  networking.firewall = {{
    allowedTCPPorts = [
      10250 # Kubelet metrics
    ];
    allowedUDPPorts = [
      8472 # Flannel VXLAN
    ];
  }};"""

    config_content = f"""{{ config, pkgs, ... }}:

{{
  imports = [
    ./hardware-configuration.nix
    ../../common/common.nix
    ../../common/k3s-cluster.nix  # Import k3s cluster settings
    ../../common/deploy-rs.nix    # Import deploy-rs specific settings
  ];

  networking.hostName = "{node_name}";
{k3s_config}

  system.stateVersion = "24.05";
}}"""

    return config_content

def create_hardware_config():
    """Create a template hardware configuration"""
    return """# This file was generated by the NixOS installation script
# and may be used by deploy-rs for system configuration.
# Do not modify this file! It will be overwritten by the next installation.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Boot configuration
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Root filesystem (OS drive)
  fileSystems."/" = {
    device = "/dev/disk/by-label/root";
    fsType = "ext4";
  };

  # Boot filesystem
  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  # Data filesystem (NVMe drive)
  fileSystems."/data" = {
    device = "/dev/disk/by-label/data";
    fsType = "ext4";
  };

  swapDevices = [ ];

  # Hardware optimization
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}"""

def generate_flake_nix(nodes):
    """Generate flake.nix with all nodes"""
    
    # Generate nixosConfigurations
    nixos_configs = []
    for node in nodes:
        node_name = node['name']
        nixos_configs.append(f"""      {node_name} = nixpkgs.lib.nixosSystem {{
        system = "x86_64-linux";
        modules = [
          ./hosts/{node_name}/configuration.nix
        ];
      }};""")
    
    # Generate deploy.nodes
    deploy_nodes = []
    for node in nodes:
        node_name = node['name']
        deploy_nodes.append(f"""      {node_name} = {{
        hostname = "{node['ip']}";
        sshUser = "satya";
        user = "root";
        profiles.system = {{
          path = deploy-rs.lib.x86_64-linux.activate.nixos self.nixosConfigurations.{node_name};
        }};
      }};""")

    flake_content = f"""{{
  description = "HomeLab NixOS Configuration";

  inputs = {{
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    deploy-rs.url = "github:serokell/deploy-rs";
  }};

  outputs = {{ self, nixpkgs, deploy-rs }}: {{
    nixosConfigurations = {{
{chr(10).join(nixos_configs)}
    }};

    deploy.nodes = {{
{chr(10).join(deploy_nodes)}
    }};
    
    checks = builtins.mapAttrs (system: deployLib: deployLib.deployChecks self.deploy) deploy-rs.lib;
  }};
}}"""

    return flake_content

def main():
    """Main function to generate all configurations"""
    print("🔧 Generating dynamic configurations from cluster.json...")
    
    # Load configuration
    config = load_cluster_config()
    nodes = config['nodes']
    server_config = config['server_config']
    agent_config = config['agent_config']
    
    # Get current node names from config
    current_nodes = {node['name'] for node in nodes}
    
    # Clean up removed nodes (declarative behavior)
    hosts_dir = Path("hosts")
    if hosts_dir.exists():
        existing_dirs = {d.name for d in hosts_dir.iterdir() if d.is_dir()}
        removed_nodes = existing_dirs - current_nodes
        
        for removed_node in removed_nodes:
            removed_dir = hosts_dir / removed_node
            print(f"🗑️  Removing {removed_dir} (not in cluster.json)")
            import shutil
            shutil.rmtree(removed_dir)
    
    # Create host directories and configurations
    for node in nodes:
        node_name = node['name']
        host_dir = Path(f"hosts/{node_name}")
        host_dir.mkdir(parents=True, exist_ok=True)
        
        # Generate configuration.nix
        config_content = create_host_config(node_name, node, server_config, agent_config)
        config_file = host_dir / "configuration.nix"
        config_file.write_text(config_content)
        print(f"✓ Generated {config_file}")
        
        # Create hardware-configuration.nix if it doesn't exist
        hardware_file = host_dir / "hardware-configuration.nix"
        if not hardware_file.exists():
            hardware_content = create_hardware_config()
            hardware_file.write_text(hardware_content)
            print(f"✓ Generated {hardware_file}")
    
    # Generate flake.nix
    flake_content = generate_flake_nix(nodes)
    flake_file = Path("flake.nix")
    flake_file.write_text(flake_content)
    print(f"✓ Generated {flake_file}")
    
    print(f"\n🎉 Successfully generated configurations for {len(nodes)} nodes!")
    
    print("\n📝 Next steps:")
    print("1. Review the generated configurations")
    print("2. Run: nix flake check")
    print("3. Deploy: deploy --remote-build .#<node>")
    print("4. Optional: python3 scripts/cleanup-nodes.py --dry-run  # Preview k3s cleanup")
    print("   Then: python3 scripts/cleanup-nodes.py  # Actually cleanup k3s")

if __name__ == "__main__":
    main()
